services:
  - type: web
    name: ai-research-report-generator
    env: python
    region: oregon
    plan: free
    buildCommand: pip3 install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    runtime:
      aptPackages:
        - build-essential
        - libxml2-dev
        - libxslt-dev
        - libjpeg-dev
        - zlib1g-dev
        - libffi-dev
